fix: error in mounted hook
The error `Error in mounted hook (Promise/async): "TypeError: this.mainStore.fetchAllQuickActions is not a function"` prevents hasCurrentUserPrincipalAndCollectionsMutation becoming true and thus the imip preview do not work.

Signed-off-by: Daniel Kesselberg <mail@danielkesselberg.de>